"""
阿宁日报 V2 - HTML 生成器
编辑部式日报，支持 AI 分析模式和降级模式
"""
import os
import re
from datetime import datetime
from pathlib import Path

from src.config import OUTPUT_DIR, SITE_META


class HTMLGenerator:
    def __init__(self, output_dir=None):
        self.output_dir = Path(output_dir or OUTPUT_DIR)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_daily_brief(self, date, analyzed_items, main_theme, commentary, raw_content="", watchpoint_reviews=None):
        items_html = ""
        for i, item in enumerate(analyzed_items, 1):
            source = item.get("source", "")
            url = item.get("url", "#")
            title = re.sub(r'^\s*\[\d+\]\s*', '', item.get("title", ""))
            title = title.lstrip("0123456789. ")
            conclusion = item.get("conclusion", "")
            signal = item.get("signal", "")
            why = item.get("why", "")
            watch = item.get("watch", "")

            source_badge = f'<span class="source-badge">{source}</span>' if source else ""

            items_html += f"""
            <article class="brief-item">
                <div class="item-header">
                    <span class="item-number">{i:02d}</span>
                    {source_badge}
                </div>
                <h3 class="item-title"><a href="{url}" target="_blank">{title}</a></h3>
                <div class="item-analysis">
                    <div class="analysis-row">
                        <span class="label">结论</span>
                        <p>{conclusion}</p>
                    </div>
                    <div class="analysis-row">
                        <span class="label">信号</span>
                        <p>{signal}</p>
                    </div>
                    <div class="analysis-row">
                        <span class="label">重要性</span>
                        <p>{why}</p>
                    </div>
                    <div class="analysis-row watch">
                        <span class="label">观察点</span>
                        <p>{watch}</p>
                    </div>
                </div>
            </article>
            """

        theme_html = ""
        if main_theme:
            theme_html = f"""
            <section class="main-theme">
                <h2>今日主线</h2>
                <div class="theme-content">{self._md_to_html(main_theme)}</div>
            </section>
            """

        commentary_html = ""
        if commentary:
            commentary_html = f"""
            <section class="commentary">
                <h2>阿宁点评</h2>
                <div class="commentary-content">{self._md_to_html(commentary)}</div>
            </section>
            """

        watchpoint_html = ""
        if watchpoint_reviews:
            wp_items = ""
            for rev in watchpoint_reviews:
                status_class = {"verified": "wp-verified", "invalidated": "wp-invalidated"}.get(rev.get("status"), "wp-progress")
                wp_items += f"""
                <div class="wp-item {status_class}">
                    <div class="wp-header">
                        <span class="wp-status">{rev.get('status_label', '⏳')}</span>
                        <span class="wp-date">{rev.get('date', '')}</span>
                    </div>
                    <p class="wp-watch">{rev.get('watch', '')}</p>
                    <p class="wp-review">{rev.get('review', '')}</p>
                </div>
                """
            watchpoint_html = f"""
            <section class="watchpoints">
                <h2>观察点回顾 <span class="count">{len(watchpoint_reviews)} 条更新</span></h2>
                {wp_items}
            </section>
            """

        degraded_html = ""
        if not analyzed_items and raw_content:
            degraded_html = f"""
            <section class="degraded">
                <div class="degraded-notice">AI 分析暂不可用，以下为原始信息</div>
                <div class="degraded-content">{self._md_to_html(raw_content)}</div>
            </section>
            """

        html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{date} {SITE_META['subtitle']} - {SITE_META['title']}</title>
    <style>{self._get_css()}</style>
</head>
<body>
    <div class="container">
        <header>
            <div class="header-top">
                <h1>{SITE_META['title']}</h1>
                <time>{self._format_date(date)}</time>
            </div>
            <p class="tagline">{SITE_META['subtitle']}</p>
        </header>

        {theme_html}

        {watchpoint_html}

        <section class="items-section">
            <h2>今日精选 <span class="count">{len(analyzed_items)} 条</span></h2>
            {items_html}
        </section>

        {degraded_html}
        {commentary_html}

        <footer>
            <p>Generated by {SITE_META['author']} | <a href="history.html">历史归档</a></p>
        </footer>
    </div>
</body>
</html>"""

        output_path = self.output_dir / f"{date}.html"
        output_path.write_text(html, encoding="utf-8")
        return str(output_path)

    def generate_empty(self, date, reason="今日暂无资讯"):
        html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{reason} - {SITE_META['title']}</title>
    <style>{self._get_css()}</style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{SITE_META['title']}</h1>
            <time>{date}</time>
        </header>
        <div class="empty">
            <p>{reason}</p>
        </div>
    </div>
</body>
</html>"""
        output_path = self.output_dir / f"{date}.html"
        output_path.write_text(html, encoding="utf-8")
        return str(output_path)

    def update_index(self, date):
        today_file = f"{date}.html"

        index_html = f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<meta http-equiv="refresh" content="0; url={today_file}">
<title>{SITE_META['title']}</title>
<script>window.location.href="{today_file}";</script>
</head><body><a href="{today_file}">跳转</a></body></html>"""
        (self.output_dir / "index.html").write_text(index_html, encoding="utf-8")

        files = sorted(self.output_dir.glob("*.html"), reverse=True)
        links = ""
        for f in files:
            if f.name in ("index.html", "history.html", "style.css"):
                continue
            links += f'<li><a href="{f.name}">{f.stem}</a></li>\n'

        history_html = f"""<!DOCTYPE html>
<html lang="zh-CN"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>历史归档 - {SITE_META['title']}</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 600px; margin: 2rem auto; padding: 1rem; background: #0f172a; color: #e2e8f0; }}
a {{ color: #60a5fa; text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
li {{ margin: 0.5rem 0; }}
</style></head><body>
<p><a href="index.html">&larr; 返回今日</a></p>
<h1>历史归档</h1>
<ul>{links}</ul>
</body></html>"""
        (self.output_dir / "history.html").write_text(history_html, encoding="utf-8")

    def _format_date(self, date_str):
        try:
            dt = datetime.strptime(date_str, "%Y-%m-%d")
            weekdays = ["周一", "周二", "周三", "周四", "周五", "周六", "周日"]
            return f"{dt.year}年{dt.month}月{dt.day}日 {weekdays[dt.weekday()]}"
        except Exception:
            return date_str

    def _md_to_html(self, text):
        lines = text.split("\n")
        result = []
        for line in lines:
            stripped = line.strip()
            if not stripped:
                continue
            elif stripped == "---":
                result.append("<hr>")
            elif stripped.startswith("### "):
                result.append(f"<h4>{self._inline_md(stripped[4:])}</h4>")
            elif stripped.startswith("## "):
                result.append(f"<h3>{self._inline_md(stripped[3:])}</h3>")
            elif stripped.startswith("- "):
                result.append(f"<li>{self._inline_md(stripped[2:])}</li>")
            else:
                result.append(f"<p>{self._inline_md(stripped)}</p>")
        return "\n".join(result)

    def _inline_md(self, text):
        text = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2" target="_blank">\1</a>', text)
        text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
        text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
        return text

    def _get_css(self):
        return """
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
    background: #0f172a;
    color: #e2e8f0;
    line-height: 1.7;
}
.container {
    max-width: 800px;
    margin: 0 auto;
    padding: 2rem 1.5rem;
}

/* Header */
header {
    margin-bottom: 2.5rem;
    padding-bottom: 1.5rem;
    border-bottom: 1px solid rgba(255,255,255,0.1);
}
.header-top {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
}
header h1 {
    font-size: 1.8rem;
    font-weight: 700;
    color: #f8fafc;
}
header time {
    font-size: 0.9rem;
    color: #94a3b8;
}
.tagline {
    font-size: 0.9rem;
    color: #64748b;
    margin-top: 0.3rem;
}

/* 今日主线 */
.main-theme {
    background: rgba(59, 130, 246, 0.08);
    border: 1px solid rgba(59, 130, 246, 0.2);
    border-radius: 12px;
    padding: 1.5rem;
    margin-bottom: 2.5rem;
}
.main-theme h2 {
    font-size: 1.1rem;
    color: #60a5fa;
    margin-bottom: 1rem;
    font-weight: 600;
}
.theme-content p {
    color: #cbd5e1;
    margin-bottom: 0.8rem;
    line-height: 1.9;
    text-align: justify;
}
.theme-content strong {
    color: #93c5fd;
    font-weight: 600;
}
hr {
    border: none;
    border-top: 1px solid rgba(255,255,255,0.08);
    margin: 1rem 0;
}

/* 条目 */
.items-section h2 {
    font-size: 1.2rem;
    color: #f8fafc;
    margin-bottom: 1.5rem;
}
.items-section .count {
    font-size: 0.85rem;
    color: #64748b;
    font-weight: 400;
}

.brief-item {
    background: rgba(255,255,255,0.03);
    border: 1px solid rgba(255,255,255,0.06);
    border-radius: 12px;
    padding: 1.5rem;
    margin-bottom: 1.2rem;
    transition: border-color 0.2s;
}
.brief-item:hover {
    border-color: rgba(59, 130, 246, 0.3);
}

.item-header {
    display: flex;
    align-items: center;
    gap: 0.8rem;
    margin-bottom: 0.8rem;
}
.item-number {
    font-size: 0.75rem;
    color: #64748b;
    font-weight: 600;
    font-family: monospace;
}
.source-badge {
    font-size: 0.7rem;
    padding: 2px 8px;
    border-radius: 4px;
    background: rgba(255,255,255,0.06);
    color: #94a3b8;
}

.item-title {
    font-size: 1.05rem;
    font-weight: 600;
    margin-bottom: 1rem;
    line-height: 1.5;
}
.item-title a {
    color: #f1f5f9;
    text-decoration: none;
}
.item-title a:hover {
    color: #60a5fa;
}
.item-title a:visited {
    color: #94a3b8;
}

.item-analysis {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
}
.analysis-row {
    display: flex;
    gap: 0.8rem;
    align-items: baseline;
}
.analysis-row .label {
    font-size: 0.75rem;
    color: #64748b;
    min-width: 3.5rem;
    font-weight: 500;
    flex-shrink: 0;
}
.analysis-row p {
    font-size: 0.9rem;
    color: #cbd5e1;
}
.analysis-row.watch .label {
    color: #d97706;
}
.analysis-row.watch p {
    color: #e5a23c;
}

/* 观察点回顾 */
.watchpoints {
    background: rgba(16, 185, 129, 0.06);
    border: 1px solid rgba(16, 185, 129, 0.15);
    border-radius: 12px;
    padding: 1.5rem;
    margin-bottom: 2.5rem;
}
.watchpoints h2 {
    font-size: 1.1rem;
    color: #10b981;
    margin-bottom: 1rem;
    font-weight: 600;
}
.watchpoints .count {
    font-size: 0.85rem;
    color: #64748b;
    font-weight: 400;
}
.wp-item {
    padding: 1rem;
    margin-bottom: 0.8rem;
    border-radius: 8px;
    background: rgba(255,255,255,0.03);
    border-left: 3px solid #64748b;
}
.wp-item.wp-verified { border-left-color: #10b981; }
.wp-item.wp-invalidated { border-left-color: #ef4444; }
.wp-item.wp-progress { border-left-color: #f59e0b; }
.wp-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 0.5rem;
}
.wp-status { font-size: 0.85rem; }
.wp-date { font-size: 0.75rem; color: #64748b; }
.wp-watch {
    font-size: 0.9rem;
    color: #94a3b8;
    margin-bottom: 0.4rem;
    font-style: italic;
}
.wp-review {
    font-size: 0.9rem;
    color: #e2e8f0;
}

/* 阿宁点评 */
.commentary {
    background: rgba(139, 92, 246, 0.06);
    border: 1px solid rgba(139, 92, 246, 0.15);
    border-radius: 12px;
    padding: 1.5rem;
    margin-top: 2.5rem;
}
.commentary h2 {
    font-size: 1.1rem;
    color: #a78bfa;
    margin-bottom: 1rem;
    font-weight: 600;
}
.commentary-content p {
    color: #cbd5e1;
    margin-bottom: 1.2rem;
    line-height: 1.9;
    text-align: justify;
}
.commentary-content h3,
.commentary-content h4 {
    color: #c4b5fd;
    margin: 1.5rem 0 0.6rem;
    font-size: 0.95rem;
}
.commentary-content strong {
    color: #e2e8f0;
    font-weight: 600;
}

/* 降级 */
.degraded {
    margin-top: 1.5rem;
}
.degraded-notice {
    background: rgba(245, 158, 11, 0.1);
    border: 1px solid rgba(245, 158, 11, 0.2);
    border-radius: 8px;
    padding: 0.8rem 1rem;
    color: #fbbf24;
    font-size: 0.85rem;
    margin-bottom: 1.5rem;
}
.degraded-content h3 {
    color: #f8fafc;
    margin: 1.5rem 0 0.8rem;
    font-size: 1rem;
}
.degraded-content h4 {
    color: #cbd5e1;
    margin: 1rem 0 0.5rem;
    font-size: 0.95rem;
}
.degraded-content li {
    margin: 0.3rem 0 0.3rem 1.5rem;
    color: #94a3b8;
    font-size: 0.9rem;
}
.degraded-content a {
    color: #60a5fa;
    text-decoration: none;
}
.degraded-content a:hover {
    text-decoration: underline;
}

/* Empty */
.empty {
    text-align: center;
    padding: 4rem 0;
    color: #64748b;
    font-size: 1.1rem;
}

/* Footer */
footer {
    text-align: center;
    margin-top: 3rem;
    padding-top: 1.5rem;
    border-top: 1px solid rgba(255,255,255,0.05);
    font-size: 0.8rem;
    color: #475569;
}
footer a { color: #64748b; text-decoration: none; }
footer a:hover { color: #94a3b8; }

/* 响应式 */
@media (max-width: 640px) {
    .container { padding: 1rem; }
    header h1 { font-size: 1.4rem; }
    .header-top { flex-direction: column; gap: 0.3rem; }
    .brief-item { padding: 1.2rem; }
    .item-title { font-size: 0.95rem; }
    .analysis-row { flex-direction: column; gap: 0.2rem; }
    .analysis-row .label { min-width: auto; }
}
"""
