"""
图片生成模块
使用 Firefly Card API 将 Markdown 内容转换为精美图片
"""
import os
import json
import base64
import requests
from typing import Dict, Any, List
from pathlib import Path
from datetime import datetime

from src.config import (
    FIREFLY_API_URL,
    FIREFLY_API_KEY,
    ENABLE_IMAGE_GENERATION,
    OUTPUT_DIR
)

class ImageGenerator:
    """Firefly Card API 图片生成器"""
    
    def __init__(self, output_dir: str = None):
        self.output_dir = Path(output_dir or OUTPUT_DIR)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
    def generate(self, news_items: List[Dict[str, Any]]) -> str:
        """
        生成分享图片
        
        Args:
            news_items: 新闻列表
            
        Returns:
            生成的图片路径
        """
        if not ENABLE_IMAGE_GENERATION:
            print("Image generation is disabled. Set ENABLE_IMAGE_GENERATION=true to enable.")
            return None
            
        if not news_items:
            return None
            
        # 构建 Markdown 内容
        markdown = self._build_markdown(news_items)
        
        # 调用 API 生成图片
        try:
            headers = {
                "Content-Type": "application/json"
            }
            if FIREFLY_API_KEY:
                headers["Authorization"] = f"Bearer {FIREFLY_API_KEY}"
                
            payload = {
                "content": markdown,
                "config": {
                    "width": 800,
                    "theme": "light",
                    "font": "SourceHanSerifCN_Bold",
                    "padding": 40
                }
            }
            
            response = requests.post(FIREFLY_API_URL, json=payload, headers=headers)
            if response.status_code == 200:
                result = response.json()
                if result.get("success"):
                    image_data = result.get("data", {}).get("image", "")
                    if image_data:
                        # 保存图片
                        date_str = datetime.now().strftime("%Y-%m-%d")
                        output_path = self.output_dir / f"{date_str}_share.png"
                        
                        # 处理 base64 前缀
                        if "base64," in image_data:
                            image_data = image_data.split("base64,")[1]
                            
                        with open(output_path, "wb") as f:
                            f.write(base64.b64decode(image_data))
                            
                        return str(output_path)
            
            print(f"Failed to generate image: {response.text}")
            return None
            
        except Exception as e:
            print(f"Error generating image: {e}")
            return None

    def _build_markdown(self, news_items: List[Dict[str, Any]]) -> str:
        """构建用于生成图片的 Markdown"""
        date_str = datetime.now().strftime("%Y-%m-%d")
        md = f"# 今日全网热点 · {date_str}\n\n"
        
        # 简单分组
        grouped = {}
        for item in news_items:
            source = item.get('source', 'Other')
            if source not in grouped: grouped[source] = []
            grouped[source].append(item)
            
        for source, items in grouped.items():
            md += f"## {source}\n"
            for item in items[:5]: # 每个源只显示前5条，防止图片太长
                md += f"- {item['title']}\n"
            md += "\n"
            
        md += "\n---\n*Generated by News Aggregator Skill*"
        return md

def generate_card_image(news_items: List[Dict[str, Any]]) -> str:
    """便捷函数：生成分享卡片"""
    generator = ImageGenerator()
    return generator.generate(news_items)
